import os
import gitit
from dotenv import dotenv_values

DOOR = dotenv_values('.door')

def make_muck(muck: str):
    gitit.grab_file(
        f"https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/garage-interior/dirty-garage-floor/{muck}.py",
        f"garage-interior/dirty-garage-floor/{muck}.py"
        )

def main():
    print()
    note_exists = os.path.exists("garage-door-note.md")
    if note_exists == True:
        garage_interior_exists = os.path.exists("/garage-interior")
        if garage_interior_exists == True:
            print("The door's already unlocked. Not much else to see here.")
            print()
        else:
            user_code = input("Please enter 4-digit passcode: ")
            print()
            if user_code == DOOR["CODE"]:
                print("Unlocking garage...")
                print()

                # Create add'l garage directories
                os.mkdirs("garage-interior/dirty-garage-floor")

                # Add files to garage-interior directory
                gitit.grab_file("https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/garage-interior/.vac-eq", "garage-interior/.vac-eq")
                gitit.grab_file("https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/garage-interior/robo-vac.py", "garage-interior/robo-vac.py")
                gitit.grab_file("https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/garage-interior/vacuum-instructions.md", "garage-interior/vacuum-instructions.md")

                # Add files to dirty-garage-floor directory
                make_muck("a-few-loose-screws")
                make_muck("air-freshener")
                make_muck("art-deco-book")
                make_muck("beadless-abacus")
                make_muck("beanbag")
                make_muck("bolts")
                make_muck("box-shaped-jello")
                make_muck("brass-tacks")
                make_muck("broken-glass")
                make_muck("brown-paper-bag")
                make_muck("busted-bifocals")
                make_muck("cardboard")
                make_muck("chipped-marble")
                make_muck("clown-college-rejection-letter")
                make_muck("coffee-stained-coaster")
                make_muck("crap")
                make_muck("crud")
                make_muck("crumbs")
                make_muck("crusty-object")
                make_muck("debris")
                make_muck("definitely-not-chocolate")
                make_muck("detritus")
                make_muck("dirt")
                make_muck("dirty-sock")
                make_muck("dust")
                make_muck("earring-stud")
                make_muck("empty-seltzer-can")
                make_muck("enigmatic-invention")
                make_muck("etch-a-sketch")
                make_muck("everyone-loves-robert-season-four-dvd-with-extra-commentary")
                make_muck("eviction-notice")
                make_muck("filled-out-madlibs")
                make_muck("final-fantasy-xxvii")
                make_muck("five-second-rule-sandwich")
                make_muck("friendship-bracelet")
                make_muck("gamegirl-advance")
                make_muck("glass-eye")
                make_muck("golfball")
                make_muck("greasy-griddle")
                make_muck("half-eaten-two-musketeers")
                make_muck("half-melted-crayon")
                make_muck("headless-doll")
                make_muck("holographic-nokemon-card")
                make_muck("inkless-pen")
                make_muck("javascript")
                make_muck("junk")
                make_muck("little-foosball-guy")
                make_muck("maybe-chocolate")
                make_muck("mood-ring")
                make_muck("motivational-cat-poster")
                make_muck("mummified-flea")
                make_muck("mysterious-cable")
                make_muck("note-to-self")
                make_muck("number-one-pencil")
                make_muck("nuts")
                make_muck("old-wiring")
                make_muck("origami-duck")
                make_muck("other-dirty-sock")
                make_muck("paperclip-shaped-like-an-s")
                make_muck("perfectly-good-umbrella")
                make_muck("permanent-marker")
                make_muck("petrified-mouse")
                make_muck("pile-of-postage-stamps")
                make_muck("ping-pong-paddle")
                make_muck("pizza-box")
                make_muck("plastic-straw")
                make_muck("priceless-artifact")
                make_muck("protractor")
                make_muck("puka-shell-necklace")
                make_muck("puzzle-piece")
                make_muck("questionable-substance")
                make_muck("rose-tinted-spectacles")
                make_muck("rusty-bucket")
                make_muck("rusty-nail")
                make_muck("sandwich-crust")
                make_muck("second-rusty-nail")
                make_muck("settlers-of-batan")
                make_muck("shipping-label")
                make_muck("shoe-string")
                make_muck("soggier-papers")
                make_muck("soggiest-papers")
                make_muck("soggy-papers")
                make_muck("spent-battery")
                make_muck("splotchy-dishrag")
                make_muck("sponge-labeled-bob")
                make_muck("styrofoam")
                make_muck("tambourine")
                make_muck("tapeless-cassette-tape")
                make_muck("thingy-three")
                make_muck("tin-foil-hat")
                make_muck("trekking-stars-fanfiction")
                make_muck("triangular-sales-brochure")
                make_muck("unlabeled-folder")
                make_muck("unmailed-mail-in-rebate")
                make_muck("unpaid-phone-bill")
                make_muck("untouched-sudoku-puzzle")
                make_muck("walkman")
                make_muck("worn-tread")
                make_muck("yellow-guitar-pick")
                
                print("Welcome.")
                print()
            else:
                print("Sorry, that is incorrect.")
                print()
    else:
        print("The garage door is firmly locked.")
        print("You see a keypad that takes a 4-digit code...")
        print("...but you don't remember The Landlord giving you any codes...")
        print()
        print("However, you do see a note taped on the door.")
        print()
        gitit.grab_file("https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/garage-door-note.md", "garage-door-note.md")
        print("Attached to the note are two small...thingies? They're hard to describe.")
        print("They're small machines of some sort.")
        print("Maybe the note will shed some light on this whole situation.")
        print()
        gitit.grab_file("https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/thingy-one.py", "thingy-one.py")
        gitit.grab_file("https://raw.githubusercontent.com/term-world/world-additions/main/week-1-additions/thingy-two.py", "thingy-two.py")

if __name__ == "__main__":
    main()